### ISSUE TITLE
Uninstalling TagUI writer

### ISSUE THREAD

**Issue by RohitY** [adegard/tagui_scripts#4]
I have used Tagui writer. Great tool indeed ! But how can I uninstall it now? there are no option to uninstall it.

**Comment by adegard** [comment]
Hi @RohitY no need of uninstaller, just delete the file (close it before tray : right click/Exit)

**Comment by RohitY** [comment]
Thanks @adegard , Apparently the file doesnot show up in windows tray. Let me explain:
- I ran writer.exe. Windows gave a security warning and I choose to continue. 
- It got enabled i.e. ctrl+left click showed dropdown
- Could not revert back since app was not shown in windows task manager or tray or hidden.
- Did a restart and it went fine.

But a great tool for TagUI.

Thanks

**Comment by adegard** [comment]
ok @RohitY 
I will add an "Exit" option in Menu dropdown in next release... 
thanks for your comment. I'm happy it's also usefull for you.

**Comment by adegard** [comment]
Exit added now in version Tagui-Writer1.02
