### ISSUE TITLE
Possible New Feature - Identifying UI Components

### ISSUE THREAD

**Issue by markjrobby** [adegard/tagui_scripts#5]
Hi,

Came across your repo and was wondering if currently with tagui scripts, I could use it to automatically identify UI components on a mobile app running on a simulator? If it possible, could it programatically interact with UI components (for e.g. if it identified a button, it would click it) and take screenshots?

**Comment by adegard** [comment]
Hi, Sorry for delay... I do not looking at it for a while.
For TagUI issues please ask on this repo: https://github.com/kelaberetiv/TagUI
