### ISSUE TITLE
Tagui writer not working

### ISSUE THREAD

**Issue by Looleek** [adegard/tagui_scripts#7]

**Comment by adegard** [comment]
@Looleek asked by email:

Dears,
i am begginer in RPA and want study something in Tagui, but i can not open tagui writer.
i dont know why. Tagui editor works fine istead of it.
Please advise what can i do in this case. i dont see any windows, only that
snip

Thank you all


Answer:

**To open Tagui Writer menu : Just press Control button + Left mouse click** inside your favorite code editor (notepad ie)
